from .attention_score_mse import AttentionScoreMSE
from .attention_probs_mse import AttentionProbsMSE
from .attention_probs_kl import AttentionProbsKL
from .embed_mse import EmbedMSELoss
from .fine_grain import FineGrainLoss
from .hard_label import HardLabel
from .hidden_mse import HiddenMSE
from .last_value_map_kl import LastValueMapKL
from .logits_mse import LogitsMSE
from .out_ce import OutCELoss
from .out_kl import OutKLLoss
from .out_l1 import OutL1Loss
from .out_cos import OutCosLoss
#from .vit_kd import ViTKDLoss
from .soft_label import SoftLabel
from .clip_cos_diff import CLIPCosDiff
from .cross_model_attn import CrossModalAtnnLoss